name: Build and deploy JAR app to Azure Web App - mydea-backend

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build (Gradle)
        run: ./gradlew -x test bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: build/libs/*.jar 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: .

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A96896ACE8F84C5DA8F6E4EA48DCD142 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E38722500C654105B16265769E4826C1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E70A5BF10B374644898B97184D148414 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mydea-backend'
          slot-name: 'Production'
          package: '*.jar'
